### ISSUE TITLE
falco - host alert

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-apps#1100] opened 2022-08-04 06:18 UTC
**Describe the bug**
Falco is generating the below host alert on a test cluster setup:

> {"output":": Notice Unexpected setuid call by non-sudo, non-root program (user=<NA> user_loginuid=-1 cur_uid= parent=<NA> command=<NA> uid=<NA> container_id=host image=<NA>) k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host","priority":"Notice","rule":"Non sudo setuid","source":"syscall","tags":["mitre_privilege_escalation","users"],"time":"", "output_fields": {"container.id":"host","container.image.repository":null,"evt.arg.uid":"<NA>","evt.time":,"k8s.ns.name":null,"k8s.pod.name":null,"proc.cmdline":"<NA>","proc.pname":null,"user.loginuid":-1,"user.name":null,"user.uid":}}

**Expected behaviour**
Alert not being triggered or an exception added if it's a know behaviour that doesn't affect our security.

**Definition of Done**
- wait until we complete the [falco v0.33 upgrade task ](https://github.com/elastisys/compliantkubernetes-apps/issues/1017)
- check if the alert is still present (check after 24h or 48h)
- if still there investigate the issue and propose a solution

**Comment by ayoubeddafali** [comment] 2023-02-13 07:54
Did the falco upgrade on my dev cluster, the alert appeared after 63 hours

**Comment by ayoubeddafali** [comment] 2023-02-14 13:56
Couldn't reproduce the alert with exact event data, seems likely that it is caused by particular daemonset. 
As for now, the alert has been triggered only once ( no spam ), and it doesn't look like we can exclude it due to lack of event details

**Comment by ayoubeddafali** [comment] 2023-02-15 16:46
I tried restarting all the cluster daemonsets one by one, and checked falco logs to see if the alert appears, but it didn't. 
Seems like the alert is a false positive, as it appeared only once since the falco upgrade, so I suggest closing this investigation, and maybe reopen it if it spams the alerts

**Closed by ayoubeddafali** 2023-02-15 16:46 UTC
Labels: falco, investigation
