### ISSUE TITLE
Full support for Swift

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#1335] opened 2022-12-16 12:05 UTC
**Is your feature request related to a problem? Please describe.**
On some clouds the S3 compatibility is lackluster where things such as multipart uploads are not fully supported among other things.

**Describe the solution you'd like**
On some openstack clouds with a poor S3 offering, openstack Swift is usually available.
I propose that we make Swift a first-class object storage solution along-side S3.
We already do have some support for Swift for Thanos and Harbor. 

Swift support is needed for
- Velero
- Fluentd
- Opensearch

**Describe alternatives you've considered**
Not having Swift as a first-class object storage solution.

**Additional context**
It might be that Swift is not supported for all components, e.g. I do not think that there is support for native swift for storing opensearch snapshots.
If this is the case it might still be good to be able to use Swift for as many components as possible even though Swift will not be a first-class object-storage solution. 

Do keep in mind that prefer authentication via openstack application credentials.

**Definition of done:**
It is possible to set object storage to swift (and s3 if swift is not supported by all components).

**Comment by cristiklein** [comment] 2023-02-09 13:22
I had an email conversation with Elastx. They confirmed that they treat the S3 API as a first-class citizen. They only asked us to configure Thanos to use the Swift API, since Thanos causes some unusual load against the S3 API. However, there is no need to systematically move away from the S3 API.

Hence, I'm closing this issue.

**Closed by cristiklein** 2023-02-09 13:22 UTC
Labels: feature
