### ISSUE TITLE
[3] Investigate using default as HNC parent ns

### ISSUE THREAD

**Issue by Pavan-Gunda** [elastisys/compliantkubernetes-apps#1213] opened 2022-09-30 07:07 UTC
**Is your feature request related to a problem? Please describe.**

Since we want to use the default namespace as the parent namespace for HNC created namespaces, we need to do an investigation to see how this could be done and what the impact is.

**Describe the solution you'd like**
We want users to be able to create namespaces using HNC controller with default as parent namespace. Update the user-facing docs on how to create delete update and listing those namespaces.

Add migration docs if needed. 

**Describe alternatives you've considered**

**Additional context**

**Definition of done:**

* A path forward for how to enable default namespace as parent namespace

**Comment by raviranjanelastisys** [comment] 2022-09-30 07:10
@Pavan-Gunda Please update if there is any changes needs to be done on the migrations docs too to make sure migrations happens smoothly

**Comment by Pavan-Gunda** [comment] 2022-09-30 07:48
I've mentioned something above that says similar "add migration docs if needed"

**Comment by aarnq** [comment] 2022-10-13 08:44
I have with limited testing applied the user-rbac to the `default` namespace, and I have primarily tested to modify using user permissions the only object I found by default in that namespace which is the `kubernetes` service.

Removing it is fine, it will come back after a few seconds, however the issue is editing.
If one would edit the service, say as simple as pointing it to the incorrect port, the service will not be reconciled and corrected automatically. This breaks fundamental functions within Kubernetes, an example would be that you wouldn't have the ability to create and delete pods since Calico can't talk to the Kubernetes API. And anything that would try to create a new connection to the Kube API using this service would face the same issue.

So the only alternative I would see is to create some highly specialised RBAC to protect it, but I don't think that is feasible. And we would be better of creating a single user namespace that they can have as a root namespace and configure their kubeconfig context to use it (which we already do).

I feel ready to close this as won't fix for this reason.

**Comment by OlleLarsson** [comment] 2022-10-14 05:54
We should also then I guess try and remove access to the default namespace for the environments in which they have been given access to it. I think there are a few.

**Comment by aarnq** [comment] 2022-10-14 07:11
Closing this. Will create an issue regarding current envs.

**Closed by aarnq** 2022-10-14 07:11 UTC
Labels: investigation
