### ISSUE TITLE
Look into other ways of handling in-progress changelog.

### ISSUE THREAD

**Issue by Zash** [elastisys/compliantkubernetes-apps#1738] opened 2023-08-25 12:09 UTC
**What should be investigated.**
Look into other ways of managing the in-progress changelog, preferably ones that reduces how often one needs to resolve merge conflicts.

![merge conflict in WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/assets/197474/d132e49e-ed3b-441f-a5d9-386f4a8c1e0d)

Some methods mentioned already:

- Extract from commit messages
- Separate files per change, concatenated together during release prep

**What artifacts should this produce.**
Recommendation on whether to switch method or stay with current way. Later: Updated docs, PR templates.

**Comment by aarnq** [comment] 2023-08-25 13:41
We have this in the pipeline, and the source of truth for changes will be PRs. 
(The issue is in a private repo as it touches internal stuff as well, and it seems it will be prioritised quite soon!)

I'll close this as duplicate.

**Closed by aarnq** 2023-08-25 13:41 UTC
Labels: investigation
