### ISSUE TITLE
[1] Opensearch admin cannot start restore

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#1741] opened 2023-08-28 11:33 UTC
**Describe the bug**:

When trying to start a restore from snapshot in opensearch with the admin user it fails with a permission error.

This was discovered when trying to follow the [disaster recovery documentation](https://elastisys.io/compliantkubernetes/operator-manual/disaster-recovery/#restore).

```console
❯ curl -kL -u "${user}:${password}" -X POST "${os_url}/_snapshot/${snapshot_repo}/${snapshot_name}/_restore?pretty" -H 'Content-Type: application/json' -d'
{
  "indices": "'${indices}'"
}
'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "no permissions for [] and User [name=admin, backend_roles=[], requestedTenant=null]"
      }
    ],
    "type" : "security_exception",
    "reason" : "no permissions for [] and User [name=admin, backend_roles=[], requestedTenant=null]"
  },
  "status" : 403
}
```

The commands before this in the guide (listing snapshots, etc) worked well, so the username, password, url, and other variables were likely correct.

**To Reproduce**:

Steps to reproduce the behaviour:

1. Follow the [disaster recovery documentation](https://elastisys.io/compliantkubernetes/operator-manual/disaster-recovery/#restore), using curl and the admin user (not devtools)
1. When trying to start a restore, notice the 403 error.

**Expected behaviour**:

The admin user should have permissions to restore a snapshot.

**Screenshots**:

**Version (add all relevant versions)**:

- Compliant Kubernetes apps version v0.21.2

**Additional context**:

**Comment by lunkan93** [comment] 2023-10-09 12:58
I have not been able to reproduce the issue on main or v0.31.2. Leaving this open to see if we encounter this in upcoming DR exercises.

**Comment by lunkan93** [comment] 2023-10-27 07:03
Closing this, as we did not encounter this in the DR exercises and I wasn't able to reproduce it. We can assume it was  caused by some environment specific issue.

**Closed by lunkan93** 2023-10-27 07:03 UTC
Labels: bug
